# Generated by Django 3.2.7 on 2021-09-14 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='time_zone',
            field=models.CharField(default=django.utils.timezone.get_current_timezone_name, max_length=50),
        ),
    ]
