# Generated by Django 3.2.7 on 2021-09-11 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210911_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcetype',
            options={'verbose_name': 'Resource Type', 'verbose_name_plural': 'Resource Types'},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='resource',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/resource'),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/resource_type'),
        ),
        migrations.CreateModel(
            name='ResourceGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(max_length=200, upload_to='images/resource_gallery')),
                ('resource', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.resource')),
            ],
            options={
                'verbose_name': 'Resource Gallery',
                'verbose_name_plural': 'Resource Galleries',
            },
        ),
    ]
